apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::764201937192:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GWEXKUJ4D35E
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::764201937192:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::764201937192:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GWEXKUJ4D35E\n  username: system:node:{{EC2PrivateDNSName}}\n  - system:masters\n  rolearn: arn:aws:iam::764201937192:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-11-20T15:26:26Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1817","uid":"14d0537b-9719-4084-9f84-2b0063bda1f3"}}
  creationTimestamp: "2022-11-20T15:26:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8545"
  uid: 14d0537b-9719-4084-9f84-2b0063bda1f3
